// Popular cities for autocomplete in travel forms
export const popularCities = [
  // Africa
  'Abidjan, Ivory Coast',
  'Accra, Ghana',
  'Addis Ababa, Ethiopia',
  'Algiers, Algeria',
  'Cairo, Egypt',
  'Cape Town, South Africa',
  'Casablanca, Morocco',
  'Dakar, Senegal',
  'Dar es Salaam, Tanzania',
  'Durban, South Africa',
  'Johannesburg, South Africa',
  'Kampala, Uganda',
  'Khartoum, Sudan',
  'Kinshasa, Democratic Republic of Congo',
  'Lagos, Nigeria',
  'Luanda, Angola',
  'Marrakech, Morocco',
  'Nairobi, Kenya',
  'Rabat, Morocco',
  'Tunis, Tunisia',

  // Asia
  'Almaty, Kazakhstan',
  'Ankara, Turkey',
  'Baghdad, Iraq',
  'Baku, Azerbaijan',
  'Bangalore, India',
  'Bangkok, Thailand',
  'Beijing, China',
  'Beirut, Lebanon',
  'Bishkek, Kyrgyzstan',
  'Brunei, Brunei',
  'Chengdu, China',
  'Chennai, India',
  'Chongqing, China',
  'Colombo, Sri Lanka',
  'Damascus, Syria',
  'Delhi, India',
  'Dhaka, Bangladesh',
  'Doha, Qatar',
  'Dubai, UAE',
  'Dushanbe, Tajikistan',
  'Guangzhou, China',
  'Hanoi, Vietnam',
  'Ho Chi Minh City, Vietnam',
  'Hong Kong, China',
  'Hyderabad, India',
  'Islamabad, Pakistan',
  'Istanbul, Turkey',
  'Jakarta, Indonesia',
  'Jeddah, Saudi Arabia',
  'Jerusalem, Israel',
  'Kabul, Afghanistan',
  'Karachi, Pakistan',
  'Kathmandu, Nepal',
  'Kolkata, India',
  'Kuala Lumpur, Malaysia',
  'Kuwait City, Kuwait',
  'Kyoto, Japan',
  'Lahore, Pakistan',
  'Macau, China',
  'Male, Maldives',
  'Manila, Philippines',
  'Muscat, Oman',
  'Mumbai, India',
  'Nanjing, China',
  'New Delhi, India',
  'Osaka, Japan',
  'Phnom Penh, Cambodia',
  'Pune, India',
  'Pyongyang, North Korea',
  'Riyadh, Saudi Arabia',
  'Sanaa, Yemen',
  'Seoul, South Korea',
  'Shanghai, China',
  'Shenzhen, China',
  'Singapore',
  'Taipei, Taiwan',
  'Tashkent, Uzbekistan',
  'Tbilisi, Georgia',
  'Tehran, Iran',
  'Tel Aviv, Israel',
  'Thimphu, Bhutan',
  'Tianjin, China',
  'Tokyo, Japan',
  'Ulaanbaatar, Mongolia',
  'Vientiane, Laos',
  'Wuhan, China',
  'Yerevan, Armenia',

  // Australia & Oceania
  'Adelaide, Australia',
  'Auckland, New Zealand',
  'Brisbane, Australia',
  'Canberra, Australia',
  'Christchurch, New Zealand',
  'Darwin, Australia',
  'Hobart, Australia',
  'Melbourne, Australia',
  'Perth, Australia',
  'Port Moresby, Papua New Guinea',
  'Suva, Fiji',
  'Sydney, Australia',
  'Wellington, New Zealand',

  // Europe
  'Amsterdam, Netherlands',
  'Athens, Greece',
  'Barcelona, Spain',
  'Belgrade, Serbia',
  'Berlin, Germany',
  'Bern, Switzerland',
  'Bratislava, Slovakia',
  'Brussels, Belgium',
  'Bucharest, Romania',
  'Budapest, Hungary',
  'Copenhagen, Denmark',
  'Dublin, Ireland',
  'Edinburgh, UK',
  'Frankfurt, Germany',
  'Geneva, Switzerland',
  'Hamburg, Germany',
  'Helsinki, Finland',
  'Kiev, Ukraine',
  'Lisbon, Portugal',
  'Ljubljana, Slovenia',
  'London, UK',
  'Luxembourg, Luxembourg',
  'Madrid, Spain',
  'Manchester, UK',
  'Milan, Italy',
  'Minsk, Belarus',
  'Monaco, Monaco',
  'Moscow, Russia',
  'Munich, Germany',
  'Naples, Italy',
  'Oslo, Norway',
  'Porto, Portugal',
  'Prague, Czech Republic',
  'Reykjavik, Iceland',
  'Riga, Latvia',
  'Rome, Italy',
  'Rotterdam, Netherlands',
  'Sarajevo, Bosnia and Herzegovina',
  'Skopje, North Macedonia',
  'Sofia, Bulgaria',
  'St. Petersburg, Russia',
  'Stockholm, Sweden',
  'Tallinn, Estonia',
  'The Hague, Netherlands',
  'Tirana, Albania',
  'Venice, Italy',
  'Vienna, Austria',
  'Vilnius, Lithuania',
  'Warsaw, Poland',
  'Zagreb, Croatia',
  'Zurich, Switzerland',

  // North America
  'Atlanta, USA',
  'Austin, USA',
  'Baltimore, USA',
  'Boston, USA',
  'Calgary, Canada',
  'Charlotte, USA',
  'Chicago, USA',
  'Cincinnati, USA',
  'Cleveland, USA',
  'Dallas, USA',
  'Denver, USA',
  'Detroit, USA',
  'Edmonton, Canada',
  'Guadalajara, Mexico',
  'Halifax, Canada',
  'Havana, Cuba',
  'Houston, USA',
  'Indianapolis, USA',
  'Kansas City, USA',
  'Las Vegas, USA',
  'Los Angeles, USA',
  'Memphis, USA',
  'Mexico City, Mexico',
  'Miami, USA',
  'Milwaukee, USA',
  'Minneapolis, USA',
  'Montreal, Canada',
  'Nashville, USA',
  'New Orleans, USA',
  'New York, USA',
  'Orlando, USA',
  'Ottawa, Canada',
  'Philadelphia, USA',
  'Phoenix, USA',
  'Pittsburgh, USA',
  'Portland, USA',
  'Quebec City, Canada',
  'Salt Lake City, USA',
  'San Antonio, USA',
  'San Diego, USA',
  'San Francisco, USA',
  'San Jose, USA',
  'Seattle, USA',
  'St. Louis, USA',
  'Tampa, USA',
  'Tijuana, Mexico',
  'Toronto, Canada',
  'Vancouver, Canada',
  'Washington DC, USA',
  'Winnipeg, Canada',

  // South America
  'Asuncion, Paraguay',
  'Barranquilla, Colombia',
  'Bogota, Colombia',
  'Brasilia, Brazil',
  'Buenos Aires, Argentina',
  'Caracas, Venezuela',
  'Cartagena, Colombia',
  'Cordoba, Argentina',
  'Guayaquil, Ecuador',
  'La Paz, Bolivia',
  'Lima, Peru',
  'Medellin, Colombia',
  'Montevideo, Uruguay',
  'Quito, Ecuador',
  'Recife, Brazil',
  'Rio de Janeiro, Brazil',
  'Rosario, Argentina',
  'Salvador, Brazil',
  'Santiago, Chile',
  'Sao Paulo, Brazil',
  'Sucre, Bolivia',
  'Valparaiso, Chile',
    // French cities - comprehensive list
  'Abbeville, France',
  'Agen, France',
  'Aix-en-Provence, France',
  'Ajaccio, France',
  'Albi, France',
  
  // Paris metropolitan area communes
  'Antony, France',
  'Argenteuil, France',
  'Asnières-sur-Seine, France',
  'Aubervilliers, France',
  'Aulnay-sous-Bois, France',
  'Bagneux, France',
  'Bagnolet, France',
  'Bobigny, France',
  'Bois-Colombes, France',
  'Bondy, France',
  'Boulogne-Billancourt, France',
  'Cachan, France',
  'Champigny-sur-Marne, France',
  'Charenton-le-Pont, France',
  'Châtillon, France',
  'Clamart, France',
  'Clichy, France',
  'Clichy-sous-Bois, France',
  'Colombes, France',
  'Courbevoie, France',
  'Créteil, France',
  'Drancy, France',
  'Épinay-sur-Seine, France',
  'Fontenay-aux-Roses, France',
  'Fontenay-sous-Bois, France',
  'Fresnes, France',
  'Garges-lès-Gonesse, France',
  'Gennevilliers, France',
  'Gentilly, France',
  'Gonesse, France',
  'Issy-les-Moulineaux, France',
  'Ivry-sur-Seine, France',
  'Le Blanc-Mesnil, France',
  'Le Kremlin-Bicêtre, France',
  'Le Perreux-sur-Marne, France',
  'Le Pré-Saint-Gervais, France',
  'Les Lilas, France',
  'Levallois-Perret, France',
  'Livry-Gargan, France',
  'Malakoff, France',
  'Maisons-Alfort, France',
  'Maisons-Laffitte, France',
  'Marnes-la-Coquette, France',
  'Montreuil, France',
  'Montrouge, France',
  'Nanterre, France',
  'Neuilly-Plaisance, France',
  'Neuilly-sur-Marne, France',
  'Neuilly-sur-Seine, France',
  'Nogent-sur-Marne, France',
  'Noisy-le-Grand, France',
  'Noisy-le-Sec, France',
  'Pantin, France',
  'Pierrefitte-sur-Seine, France',
  'Puteaux, France',
  'Romainville, France',
  'Rosny-sous-Bois, France',
  'Rueil-Malmaison, France',
  'Saint-Cloud, France',
  'Saint-Denis, France',
  'Saint-Mandé, France',
  'Saint-Maurice, France',
  'Saint-Ouen, France',
  'Sceaux, France',
  'Stains, France',
  'Suresnes, France',
  'Thiais, France',
  'Vanves, France',
  'Villejuif, France',
  'Villemomble, France',
  'Villeneuve-la-Garenne, France',
  'Villeneuve-Saint-Georges, France',
  'Vincennes, France',
  'Vitry-sur-Seine, France',
  
  // Extended Paris region (Île-de-France)
  'Argenteuil, France',
  'Cergy, France',
  'Évry, France',
  'Meaux, France',
  'Melun, France',
  'Pontoise, France',
  'Saint-Germain-en-Laye, France',
  'Sartrouville, France',
  'Versailles, France',
  
  // Bordeaux metropolitan area communes
  'Ambès, France',
  'Ambarès-et-Lagrave, France',
  'Artigues-près-Bordeaux, France',
  'Bassens, France',
  'Bègles, France',
  'Blanquefort, France',
  'Le Bouscat, France',
  'Bruges, France',
  'Carbon-Blanc, France',
  'Cenon, France',
  'Eysines, France',
  'Floirac, France',
  'Gradignan, France',
  'Le Haillan, France',
  'Lormont, France',
  'Mérignac, France',
  'Parempuyre, France',
  'Pessac, France',
  'Saint-Aubin-de-Médoc, France',
  'Saint-Louis-de-Montferrand, France',
  'Saint-Médard-en-Jalles, France',
  'Saint-Vincent-de-Paul, France',
  'Talence, France',
  'Villenave-d\'Ornon, France',
  
  // Extended Bordeaux region (Gironde)
  'Arcachon, France',
  'Blaye, France',
  'Cadillac, France',
  'La Réole, France',
  'Langon, France',
  'Libourne, France',
  'Pauillac, France',
  'Saint-Émilion, France',
  'Saint-Julien-Beychevelle, France',
  'Soulac-sur-Mer, France',
  'Alès, France',
  'Amiens, France',
  'Angers, France',
  'Angoulême, France',
  'Annecy, France',
  'Antibes, France',
  'Arles, France',
  'Arras, France',
  'Auch, France',
  'Aurillac, France',
  'Auxerre, France',
  'Avignon, France',
  'Bar-le-Duc, France',
  'Bastia, France',
  'Bayonne, France',
  'Beauvais, France',
  'Belfort, France',
  'Besançon, France',
  'Béziers, France',
  'Biarritz, France',
  'Blois, France',
  'Bordeaux, France',
  'Boulogne-sur-Mer, France',
  'Bourges, France',
  'Brest, France',
  'Brive-la-Gaillarde, France',
  'Caen, France',
  'Calais, France',
  'Cannes, France',
  'Carcassonne, France',
  'Castres, France',
  'Chalon-sur-Saône, France',
  'Châlons-en-Champagne, France',
  'Chambéry, France',
  'Charleville-Mézières, France',
  'Chartres, France',
  'Châteauroux, France',
  'Cherbourg, France',
  'Clermont-Ferrand, France',
  'Colmar, France',
  'Compiègne, France',
  'Créteil, France',
  'Dax, France',
  'Dijon, France',
  'Douai, France',
  'Dunkerque, France',
  'Épinal, France',
  'Évreux, France',
  'Foix, France',
  'Fréjus, France',
  'Gap, France',
  'Grenoble, France',
  'Guéret, France',
  'La Rochelle, France',
  'La Roche-sur-Yon, France',
  'Laon, France',
  'Laval, France',
  'Le Havre, France',
  'Le Mans, France',
  'Le Puy-en-Velay, France',
  'Lens, France',
  'Libourne, France',
  'Lille, France',
  'Limoges, France',
  'Lons-le-Saunier, France',
  'Lorient, France',
  'Lourdes, France',
  'Lyon, France',
  'Mâcon, France',
  'Marseille, France',
  'Meaux, France',
  'Melun, France',
  'Mende, France',
  'Metz, France',
  'Meulan, France',
  'Millau, France',
  'Mont-de-Marsan, France',
  'Montauban, France',
  'Montbéliard, France',
  'Montluçon, France',
  'Montpellier, France',
  'Mulhouse, France',
  'Nancy, France',
  'Nanterre, France',
  'Nantes, France',
  'Narbonne, France',
  'Nevers, France',
  'Nice, France',
  'Nîmes, France',
  'Niort, France',
  'Orange, France',
  'Orléans, France',
  'Paris, France',
  'Pau, France',
  'Périgueux, France',
  'Perpignan, France',
  'Poitiers, France',
  'Pontoise, France',
  'Privas, France',
  'Quimper, France',
  'Reims, France',
  'Rennes, France',
  'Rodez, France',
  'Rouen, France',
  'Saint-Brieuc, France',
  'Saint-Dizier, France',
  'Saint-Étienne, France',
  'Saint-Lô, France',
  'Saint-Malo, France',
  'Saint-Nazaire, France',
  'Saint-Omer, France',
  'Saint-Quentin, France',
  'Salon-de-Provence, France',
  'Sedan, France',
  'Sens, France',
  'Soissons, France',
  'Strasbourg, France',
  'Tarbes, France',
  'Thonon-les-Bains, France',
  'Toulon, France',
  'Toulouse, France',
  'Tours, France',
  'Troyes, France',
  'Tulle, France',
  'Valence, France',
  'Valenciennes, France',
  'Vannes, France',
  'Verdun, France',
  'Versailles, France',
  'Vesoul, France',
  'Vichy, France',
  'Vienne, France',
  'Villeurbanne, France'
];
